attributes:

  # general data set description
  conventions: 'CF-1.7'
  version: ''
  title: 'Rodsand2 wind data'
  creator: 'Data delivered by the OWA consortium. Data analysis done by Fernando Borbon <fborbon@cener.com>'
  references: ''
  site: 'Rodsand2'
  general_comment: 'Wind data time series'
  institution: 'CENER'

  # data description
  data_processing_history: ''

