attributes:

  # general data set description
  conventions     : 'CENER'
  version         : '1.0'
  title           : 'Title'
  creator         : 'Pawel Gancarski'
  references      : ''
  site            : 'Wind farm name'
  general_comment : 'Data delivered by ...'
  institution     : 'CENER'

  # data description
  data_processing_history: 'Data analysis done by ...'


